# ---------------------------------------------------------------------------
# Character Settings
# ---------------------------------------------------------------------------

# AutoLoot enable. True to enable, False to disable
AutoLoot = False

# If False herbs will drop on ground even if AutoLoot is enabled
AutoLootHerbs = False

# Auto loot from Raid Boss's drop
AutoLootBoss = False

# AutoLearnSkills: True to enable, False to disable
AutoLearnSkills = True

# AutoLearn DivineInspiration: True to enable, False to disable
AutoLearnDivineInspiration = False

# Life crystal needed to learn clan skills
LifeCrystalNeeded = True

# Spell Books needed to learn skills
SpBookNeeded = False
# Books needed to enchant skills
EnchantSkillSpBookNeeded = True
# Books needed to Divine Inspiration
DivineInspirationSpBookNeeded = True

# Alternative skill learn rules:
# - all classes can learn all skills
# - skills of another class costs x2 SP
# - skills of another race costs x2 SP
# - skills of fighters/mages costs x3 SP
AltGameSkillLearn = False

# Number of allowed Subclasses
AllowedSubclass = 3

# Starting level for subclasses.
# Default: 40
BaseSubclassLevel = 40

# Maximum subclass level. 81 is level 80 99%
# Default: 81
MaxSubclassLevel = 81

# Allow player sub-class addition without checking for unique quest items.
AltSubClassWithoutQuests = False

# Restore Buffs On Subclass Change.
# IMPORTANT: It's better put it False to avoid exploit
AltRestoreEffectOnSub = False

# When you made damage to a mob and are inside this range, you will be considered as player to reward.
# Checks for party range to mob to calculate rewards(exp, items).
# Default: 1500
AltPartyRange = 1500

# Weight Limit multiplier - default 1
# If >1 - Weight Limit Double
AltWeightLimit = 1

# If XP loss (and deleveling) is enabled, default is 'true'
Delevel = True

# If disabled, magic dmg has always 100% chance of success, default is 'true'
MagicFailures = True

# Alternative cancel of attack (bow, cast, all)
AltGameCancelByHit = cast

# Alternative rules for shields - if they block, the damage is powerAtk-shieldDef,
# otherwise it's powerAttack / (shieldDef + powerDef)
AltShieldBlocks = False

# Alternative Rate Value for Perfect Shield Block Rate.
AltPerfectShieldBlockRate = 5

# Alternative AltGameMobAttackAI, like C1
AltGameMobAttackAI = False

# Alternative mob behavior in peace zones 
# Default = True; Set to False to prevent mobs from auto-agro against players in peace zones  
AltMobAgroInPeaceZone = True

# Alternative Freight mode. If true, freights can be withdrawed from any place.
# Also, possibility to change Freight price (in adena) for each item slot in freight.
# NOTE: AltGameFreightPrice WILL NOT change the value shown to the player, but the
# player will actually get charged for the value set in here.
AltGameFreights = True
AltGameFreightPrice = 1000

# Alternative Xp/Sp rewards, if not 0, then calculated as 2^((mob.level-player.level) / coef),
# A few examples for "AltGameExponentXp = 5." and "AltGameExponentSp = 3."
# diff = 0 (player and mob has the same level), XP bonus rate = 1, SP bonus rate = 1
# diff = 3 (mob is 3 levels above), XP bonus rate = 1.52, SP bonus rate = 2
# diff = 5 (mob is 5 levels above), XP bonus rate = 2, SP bonus rate = 3.17
# diff = -8 (mob is 8 levels below), XP bonus rate = 0.4, SP bonus rate = 0.16
AltGameExponentXp = 0
AltGameExponentSp = 0

# Use tiredness (instead of combat points)
AltGameTiredness = False

# Allow free teleportation around the world.
AltFreeTeleporting = False

# Set true for disallow recommend character twice or more a day
AltRecommend = False

# Alternative Max Recommendation Number
AltMaxRecommendationNumber = 255

# Maximum number of chars per account - Default 7 (0 = unlimited [7 is the client limit])
CharMaxNumber = 7

# Maximum level players who can not be attacked
MaxLevelNewbie = 20

# When char lost newbie status > =  value
MaxLevelNewbieStatus = 40

# Disable tutorial on new player enter into Game
# Please remember its sometimes important to novice players
# Default: False
DisableTutorial = False

# Amount of adena/AA that a new character is given
StartingAdena = 0
StartingAncientAdena = 0

# Enable this if you want the below configuration to work.
# Default: False
CustomStarterItemsEnabled = False
# Starting itens for fighter's classes
StartingCustomItemsFighter = 57,1000;
# Starting itens for mage's classes
StartingCustomItemsMage = 57,1000;

# Inventory space limits
# All race without dwarf
MaximumSlotsForNoDwarf = 80
# Dwarf race
MaximumSlotsForDwarf = 100
# GM char
MaximumSlotsForGMPlayer = 250

# Warehouse space limits (Must be < 300 for prevent client crash)
# Dwarfs will get bonus from lvl 60
MaximumWarehouseSlotsForDwarf = 120
MaximumWarehouseSlotsForNoDwarf = 100
MaximumWarehouseSlotsForClan = 200
MaximumFreightSlots = 20

# The maximum number of slots for the purchase / sale (for dwarves and other races)
# By default, dwarf 5 slots, the other 4 races
MaxPvtStoreSlotsDwarf = 5
MaxPvtStoreSlotsOther = 4

# % regeneration of normal regeneration speed
HpRegenMultiplier = 100
MpRegenMultiplier = 100
CpRegenMultiplier = 100

# Enable keyboard movement.
# Retail: True
KeyboardMovement = True

# Unstuck interval, seconds, default is 300 sec.
UnstuckInterval = 300

# Player Protection on login in seconds, 0 for disabled
PlayerSpawnProtection = 0

# Player Protection after teleporting, 0 for disabled
PlayerTeleportProtection = 0

# Player Protection from (agro) mobs after getting up from fake death; in seconds, 0 for disabled
PlayerFakeDeathUpProtection = 0

# If True, the following deep blue mobs' drop penalties will be applied:
# - When player's level is 9 times greater than mob's level, drops got divided by 3
# - After 9 lvl's of difference between player and deep blue mobs, drop chance is
# lowered by 9% each lvl that difference increases. (9lvls diff = -9%; 10lvls diff = -18%; ...)
# NOTE1: These rules are applied to both normal and sweep drops
# NOTE2: These rules ignores the server's rate when drop is of adena type (Complies with retail server)
UseDeepBlueDropRules = True

# PARTY XP DISTRIBUTION
# The first option can be set to auto, percentage, level, none.
# When is "auto" member of the party receives less Exp / SP, where its level is low
# If the party received a bonus for him (30% for 2 members of the party)
# In this case, he will not get Exp / SP of the party, and will not receive a bonus party
# Not used quite too high values of the parameter "percentage"!
# Not used quite too low values of the parameter "level"!
# If you do not want to be the distribution of XP for the members of the Party
# Just put "none". Default:, 3.0, 30
PartyXpCutoffMethod = auto
PartyXpCutoffPercent = 3.0
PartyXpCutoffLevel = 30

# Levels restore HP, MP, and CP after death
# Values are specified in percentage
RespawnRestoreCP = 70
RespawnRestoreHP = 70
RespawnRestoreMP = 70

# Allow random regeneration in cities, indicating the maximum displacement
# From the main origin.
RespawnRandomInTown = True
RespawnRandomMaxOffset = 20

# Allow player to send petition?
PetitioningAllowed = True
# The number of petitions per session
MaxPetitionsPerPlayer = 5
# The number of petitions, which may consider GM
MaxPetitionsPending = 25

# Chance to get Death Penalty
DeathPenaltyChance = 20

# If True, when effects of the same stack group are used, lesser
# effects will be canceled if stronger effects are used. New effects
# that are added will be canceled if they are of lesser priority to the old one.
# If False, they will not be canceled, and it will switch to them after the
# stronger one runs out, if the lesser one is still in effect.
CancelLesserEffect = True

# Keep the effects buffs and debuff when you exit the game
StoreSkillCooltime = True

# Character name restriction
# Disallow characters to have a name which contains the words.
# Split them with ",". Example: announcements,announce...
ForbiddenNames = annou,ammou,amnou,anmou,anou,amou


# ---------------------------------------------------------------------------
#  Buffs
# ---------------------------------------------------------------------------
# Maximum number of buffs (default = 20 + 4 Divine Inspiration in C5)
MaxBuffAmount = 40
# Maximum number of debuffs 
MaxDebuffAmount = 6


# --------------------------------------
#  Alternative time buffs
# --------------------------------------
# When the reads, buff, and their duration.
# Default: False
EnableModifySkillDuration = True
# Format: id_skill time; id_skill2, time2 ;....
# Example:
#SkillDurationList = 264,7200;265,7200;266,7200;267,7200;268,7200;\
#269,7200;270,7200;304,7200;305,7200;306,7200;308,7200;349,7200;\
#363,7200;364,7200;529,7200;271,7200;272,7200;273,7200;274,7200;\
#275,7200;276,7200;277,7200;307,7200;309,7200;310,7200;311,7200;\
#305,7200;366,7200;530,7200;365,7200;\
#1086,7200;1240,7200;1242,7200;1243,7200;1388,7200;1389,7200;336,7200;\
#1035,7200;1043,7200;1044,7200;1062,7200;1268,7200;1040,7200;1393,7200;\
#1077,7200;1078,7200;1085,7200;1204,7200;1036,7200;1045,7200;1048,7200;\
#1007,7200;1006,7200;1009,7200;1251,7200;1252,7200;1253,7200;1307,7200;\
#1284,7200;1308,7200;1309,7200;1310,7200;1390,7200;1391,7200;1362,7200;\
#1303,7200;1087,7200;1259,7200;1059,7200;1311,7200;1033,7200;1002,7200;\
#1068,7200;1397,7200;1032,7200;1189,7200;1191,7200;1182,7200;1365,7200;\
#1010,7200;1282,7200;1004,7200;1008,7200;1249,7200;1250,7200;1260,7200;\
#1261,7200;1364,7200;1259,7200;1073,7200;1257,7200;1304,7200;1460,7200;\
#1353,7200;1354,7200;1003,7200;1005,7200;\
#1352,7200;1442,7200;1392,7200;\
#1355,7200;1356,7200;1357,7200;1363,7200;1461,7200;1413,7200;1414,7200
SkillDurationList = 264,7200;265,7200;266,7200;267,7200;268,7200;\
#269,7200;270,7200;304,7200;305,7200;306,7200;308,7200;349,7200;\
#363,7200;364,7200;529,7200;271,7200;272,7200;273,7200;274,7200;\
#275,7200;276,7200;277,7200;307,7200;309,7200;310,7200;311,7200;\
#305,7200;366,7200;530,7200;365,7200;\
#1086,7200;1240,7200;1242,7200;1243,7200;1388,7200;1389,7200;336,7200;\
#1035,7200;1043,7200;1044,7200;1062,7200;1268,7200;1040,7200;1393,7200;\
#1077,7200;1078,7200;1085,7200;1204,7200;1036,7200;1045,7200;1048,7200;\
#1007,7200;1006,7200;1009,7200;1251,7200;1252,7200;1253,7200;1307,7200;\
#1284,7200;1308,7200;1309,7200;1310,7200;1390,7200;1391,7200;1362,7200;\
#1303,7200;1087,7200;1259,7200;1059,7200;1311,7200;1033,7200;1002,7200;\
#1068,7200;1397,7200;1032,7200;1189,7200;1191,7200;1182,7200;1365,7200;\
#1010,7200;1282,7200;1004,7200;1008,7200;1249,7200;1250,7200;1260,7200;\
#1261,7200;1364,7200;1259,7200;1073,7200;1257,7200;1304,7200;1460,7200;\
#1353,7200;1354,7200;1003,7200;1005,7200;\
#1352,7200;1442,7200;1392,7200;\
#1355,7200;1356,7200;1357,7200;1363,7200;1461,7200;1413,7200;1414,7200


# ---------------------------------------------------------------------------
#  Class Master
# ---------------------------------------------------------------------------
# Allow Change Class with ClassMaster 
AllowClassMasters = True
# Allow Upgrade Strider with ClassMaster 
AllowClassMastersStriderUpdate = False

# Allow to define which class is allowed to be assigned through class master
AllowClassMastersFirstClass = True
AllowClassMastersSecondClass = True
AllowClassMastersThirdClass = True

# Config for special Class Master npc that can change players occupation
# If you need change occupation only use quest then set this to False (Default)
# Syntax: occupation number;[required item id(count)],[],...;[reward item id(count)],[],...;occupation number...
# Examples:
#
# ConfigClassMaster = 1;[57(100000)];[];2;[57(1000000)];[];3;[57(10000000)],[5575(1000000)];[6622(1)]
# 1st occupation change for 100.000 Adena (item id 57)
# 2nd occupation change for 1.000.0000 Adena (item id 57)
# 3rd occupation change for 10.000.0000 Adena (item id 57) and 1.000.000 Ancient Adena (item id 5575)
# On 3rd occupation change player will be rewarded with 1 Book of Giants (item id 6622) 
#
# ConfigClassMaster = 1;[];[];2;[];[];3;[];[]
# 1st, 2nd, 3rd occupation change for free, without rewards
ConfigClassMaster = 1;[57(100000)];[];2;[57(1000000)];[];3;[57(10000000)],[5575(100000)] 

# Class Manager Handled Remotely at Level 20/40/76
AllowRemoteClassMasters = False


# ---------------------------------------------------------------------------
# Voice-command for turning off XP-gain
# ---------------------------------------------------------------------------
# Player can use .xpoff to disable XP-gain, and .xpon to enable again.
# Default: False
EnableExpGainCommands = False
